services:
  - type: web
    name: django-web-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn house.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: house.settings
      - key: SECRET_KEY
        generateValue: true
